#Label the image
LABEL PROJECT="DIMBLR" \
APPS= "MongoDB" \
OS_TYPE= "Linux" \
OS_DIST= "Alpine" \
OS_VERSION= "8.8.1" \
DESCRIPTION= "Base Server Image for NodeJS" \
CREATOR= "Buck Nightwalker" \
MAINTAINER= "DIMBLR Team"
